name: Extra Achievements
version: 0.0.1-1.8.7
author: PopThosePringles (pixeldepth.net)
main: net.pixeldepth.extra_achievements.Extra_Achievements

commands:
  achievements:
    description: Gives you a book showing achievments earned and progress.
    usage: /achievements
